### ISSUE TITLE
Installation On Windows7

### ISSUE THREAD

**Issue by subu1979** [foradian/fluxday#15]
Please find the below command execution

c:\Projects\fluxday>bundle install
Fetching https://github.com/stpnlr/omniauth-fluxapp.git

Nothing happening after waiting for long time. Can someone help

**Comment by subu1979** [comment]
Please find the complete log

c:\Projects\fluxday>bundle install
Fetching https://github.com/stpnlr/omniauth-fluxapp.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies.............................................
Using rake 11.2.2
Using i18n 0.7.0
Using minitest 4.7.5
Using multi_json 1.12.1
Using thread_safe 0.3.5
Using tzinfo 0.3.50
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.5
Using mime-types 1.25.1
Using polyglot 0.3.5
Using activerecord-deprecated_finders 1.0.4
Using arel 4.0.2
Using bcrypt 3.1.11
Using bundler 1.12.5
Using cancancan 1.15.0
Using json 1.8.3
Using mimemagic 0.3.1
Using cocoon 1.2.9
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using thor 0.19.1
Using daemons 1.2.3
Using orm_adapter 0.5.0
Using eventmachine 1.2.0.1
Using multipart-post 2.0.0
Using sass 3.2.19
Using hashie 3.4.4
Using hike 1.2.3
Using hirb 0.7.3
Using jwt 1.5.1
Installing libv8 3.16.14.15 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/RailsInstaller/Ruby2.2.0/bin/ruby.exe -r ./siteconf20160628-7916-1isk02l.rb extconf.rb
creating Makefile
The system cannot find the path specified.
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:86:in `setup_python!': libv8 requires python 2 to
RuntimeError)
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:53:in `build_libv8!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/location.rb:24:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.15 for inspection.
Results logged to C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/libv8-3.16.14.15/gem_make.out
Using mini_magick 4.5.1
Using multi_xml 0.5.5
Using mysql2 0.3.21
Using tilt 1.4.1
Using ref 2.0.0
Using wicked_pdf 1.0.6
Using will_paginate 3.1.0
Using activesupport 4.0.3
Using rack-test 0.6.3
Using warden 1.2.6
Using treetop 1.4.15
Using rdoc 4.2.2
Using coffee-script 2.4.1
Using uglifier 3.0.0
Using select2-rails 3.5.4
Using thin 1.7.0
Using faraday 0.9.2
Using omniauth 1.3.1
An error occurred while installing libv8 (3.16.14.15), and Bundler cannot
continue.
Make sure that `gem install libv8 -v '3.16.14.15'` succeeds before bundling.

c:\Projects\fluxday>

**Comment by tachyons** [comment]
Install python2 and try again
http://stackoverflow.com/questions/21372637/installing-python-2-7-on-windows-8

**Comment by subu1979** [comment]
Hi Team,

Solved by commenting the following gem file

#gem "therubyracer"
