### ISSUE TITLE
What server distribution yours install demo?

### ISSUE THREAD

**Issue by ecrmweb** [foradian/fluxday#23]
I try many linux server unsuccessfully

Centos 6.8
Ubuntu 12.04
Ubuntu 16.10

First problem ruby 2.1.0 is very older and not have support any more

**Comment by 1kidvidiot** [comment]
Same here - never ran, tried Debian 9, Ubuntu 18.04 - 01

**Comment by ismudnx** [comment]
We have recently locked the gem versions. This is working now.
