### ISSUE TITLE
Unable to log into fluxday after installation

### ISSUE THREAD

**Issue by foppedisano** [foradian/fluxday#30]
Goodmorning,
I'm trying to install fluxday from source.
I followed the guide and I arrived at the point in which the system serves the homepage at localhost:3000

Unforutnately, we trying to enter with the credentials (admin@fluxday.io, password) does not get me into the portal.

Can you help me?

Thank you very much

Francesco

**Comment by nickmc01** [comment]
Ensure that you ran rake db:seed prior to logging into the application.

**Comment by nicos-hub** [comment]
Hi all,

I've the same trouble after installation, I can't login into fluxday with initial login and password, I stay on sign_in page.
rake db:seed was done and I see user admin@fluxday.io in the database.
Nothing happens in development.log when I try to connect.

Anyone has news about that?

Thanks in advance.

**Comment by nicos-hub** [comment]
On my side problem was Internet Explorer 11 (with and without compatibility mode it doesn't work) but all works fine with other browsers: Iceweasel, Firefox, Chrome...

**Comment by RubyistCTRLDYT** [comment]
I got the same problem  I work with firefox , after I create a new user   I cannot login anymore

**Comment by 1kidvidiot** [comment]
I was never able to get even this far, tried it in Ubuntu Server 18.04 and .10, also Debian 9 several times, always broke at dependencies of ruby and bundler versions

**Comment by Navinnair** [comment]
> I was never able to get even this far, tried it in Ubuntu Server 18.04 and .10, also Debian 9 several times, always broke at dependencies of ruby and bundler versions

fixed gem version issues
