### ISSUE TITLE
rake db:create issue

### ISSUE THREAD

**Issue by priyolahiri** [foradian/fluxday#39]
`/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.0.3/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'devise'.
Gem Load Error is: ActiveSupport::Duration can't be coerced into Integer
Backtrace for gem load error is:
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.0.3/lib/active_support/core_ext/numeric/time.rb:50:in `*'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.0.3/lib/active_support/core_ext/numeric/time.rb:50:in `days'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.0.3/lib/active_support/core_ext/numeric/time.rb:55:in `weeks'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/devise-3.2.4/lib/devise.rb:131:in `<module:Devise>'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/devise-3.2.4/lib/devise.rb:8:in `<top (required)>'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/home/priyo/apps/fluxday/config/application.rb:8:in `<top (required)>'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/priyo/apps/fluxday/Rakefile:4:in `<top (required)>'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/priyo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/priyo/.rbenv/versions/2.4.1/bin/rake:22:in `load'
/home/priyo/.rbenv/versions/2.4.1/bin/rake:22:in `<main>'
Bundler Error Backtrace:
/home/priyo/apps/fluxday/config/application.rb:8:in `<top (required)>'
/home/priyo/apps/fluxday/Rakefile:4:in `<top (required)>'
TypeError: ActiveSupport::Duration can't be coerced into Integer
/home/priyo/apps/fluxday/config/application.rb:8:in `<top (required)>'
/home/priyo/apps/fluxday/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)`

This happens with Ruby version 2.4.0. My server is Ubuntu 16.04 where older ruby installs fail because of newer openssl libraries.

**Comment by tachyons** [comment]
Ruby 2.4 isn't compatible with fluxday, use the ruby version mentioned in the readme file
