### ISSUE TITLE
rake db:create fails while installation

### ISSUE THREAD

**Issue by petrk94** [foradian/fluxday#44]
Hello, 

Im trying to install fluxday on my server, but it interrupt while rake db:migrate (even bundle exec rake db:migrate fails)

Gems:
>bundle update
Fetching https://github.com/stpnlr/omniauth-fluxapp.git
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...........
Using rake 12.3.0
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using minitest 4.7.5
Using multi_json 1.13.1
Using thread_safe 0.3.6
Using tzinfo 0.3.53
Using activesupport 4.0.3
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.0.3
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.5
Using actionmailer 4.0.3
Using activemodel 4.0.3
Using activerecord-deprecated_finders 1.0.4
Using arel 4.0.2
Using activerecord 4.0.3
Using bcrypt 3.1.11
Using bundler 1.16.1
Using cancancan 1.17.0
Using carrierwave 1.2.2
Using cocoon 1.2.11
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using coffee-script 2.4.1
Using thor 0.20.0
Using railties 4.0.3
Using coffee-rails 4.0.1
Using daemons 1.2.6
Using orm_adapter 0.5.0
Using warden 1.2.7
Using devise 3.2.4
Using doorkeeper 1.1.0
Using eventmachine 1.2.5
Using multipart-post 2.0.0
Using faraday 0.12.2
Using sass 3.2.19
Using foundation-rails 5.2.1.0
Using friendly_id 5.0.5
Using hashie 3.5.7
Using hike 1.2.3
Using hirb 0.7.3
Using jbuilder 1.5.3
Using jquery-rails 3.1.4
Using turbolinks 2.2.1
Using jquery-turbolinks 2.0.2
Using json 1.8.6
Using jwt 1.5.6
Using libv8 3.16.14.19 (x86_64-linux)
Using mini_magick 4.8.0
Using multi_xml 0.6.0
Using mysql2 0.3.21
Using oauth2 1.4.0
Using omniauth 1.4.2
Using omniauth-oauth2 1.5.0
Using omniauth-fluxapp 0.0.1 from https://github.com/stpnlr/omniauth-fluxapp.git (at master@687537d)
Using omniauth-google-oauth2 0.5.2
Using polyamorous 1.3.2
Using tilt 1.4.1
Using sprockets 2.12.4
Using sprockets-rails 2.0.1
Using rails 4.0.3
Using ransack 1.8.4
Using rdoc 4.3.0
Using ref 2.0.0
Using sass-rails 4.0.5
Using sdoc 0.4.2
Using select2-rails 3.5.4
Using therubyracer 0.12.3
Using thin 1.7.2
Using uglifier 4.1.3
Using wicked_pdf 1.1.0
Using will_paginate 3.1.6
Bundle updated!

Ruby Version:
$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]

This is the error message I get:
/vendor/bundle/gems/activesupport-4.0.3/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'devise'.
Gem Load Error is: ActiveSupport::Duration can't be coerced into Integer
Backtrace for gem load error is:
vendor/bundle/gems/activesupport-4.0.3/lib/active_support/core_ext/numeric/time.rb:50:in `*'
vendor/bundle/gems/activesupport-4.0.3/lib/active_support/core_ext/numeric/time.rb:50:in `days'
vendor/bundle/gems/activesupport-4.0.3/lib/active_support/core_ext/numeric/time.rb:55:in `weeks'
vendor/bundle/gems/devise-3.2.4/lib/devise.rb:131:in `<module:Devise>'
vendor/bundle/gems/devise-3.2.4/lib/devise.rb:8:in `<top (required)>'

I hope you can help
Im not able to use docker on my shared host Server

thanks

**Comment by tachyons** [comment]
Try ruby 2.1.0 , latest version of ruby is not compatible

**Comment by petrk94** [comment]
@tachyons 
I think I will break it up.
ruby 2.1.0 is not longer support by my shared hosting provider, due End of Life, I tried the oldest one available, ruby 2.2, but it need to change the rake from 12.3.0 to 10.4.2, rake db:create works without a problem, but rake db:migrate fails due 
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: NO)

Just saw now that it needs root, but its only short in the text, so meh, doesnt work, shame, I really liked the design of it.

**Comment by tachyons** [comment]
That is just default, you can set your own MySQL username and password in config/database.yml. infact it is recommended to change it than using the default credentials

**Comment by petrk94** [comment]
I have used the mysql credentials and put the mysql + version into gem file. Getting the same error, what can I do?

[digiharz@norma config]$ rake db:migrate
(in /var/www/virtual/xxx/xxx.de)
/var/www/virtual/xxx/xxx.de/vendor/bundle/gems/activesupport-4.0.3/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: NO)

**Comment by tachyons** [comment]
Not in gentile, password is to be set in 
config/database.yml file

You are missing this step given in the readme 

Update the credentials in database.yml with actual values.

**Comment by petrk94** [comment]
I have already used the database.yml, but get the same error
![unbenannt](https://user-images.githubusercontent.com/19719052/34931682-3867107e-f9d0-11e7-95ab-a7de32dbc9c7.PNG)

**Comment by tachyons** [comment]
ENV is for reading from shell environment variables, if you want to specify MySQL credentials directly there, then no need to use ENV

password: 'yourmysqlpasswordhere' will be enough

**Comment by petrk94** [comment]
@tachyons 
thanks now it works, but as admin Im unable to create tasks and this is not really great
