### ISSUE TITLE
Password reset functionality not available?

### ISSUE THREAD

**Issue by dtryan123** [foradian/fluxday#46]
No Admin or TeamLead reset functionality for local subordinate user. Can it be done from database?

**Comment by ismudnx** [comment]
You can do that from the rails console. Not db, since password is encrypted and stored.

``user = User.find_by_email('#someemail')
``user.update(password: 'password', password_confirmation: 'password')

**Comment by dtryan123** [comment]
Thank you! Appreciate the feedback.
