### ISSUE TITLE
installation on linux 

### ISSUE THREAD

**Issue by Amanimasila** [foradian/fluxday#50]
Please am very new in ruby and rails, I need help on how to  install fluxday

**Comment by 1kidvidiot** [comment]
It doesnt seem to be stable, relying on ruby dependencies that are very old and outdated, results in broken installs, have tried it on several Ubuntu and Debian installs and none worked - breaks between ruby and bundler versions, one wont support the other - I was unable to ever get it running after 5-6 attempts
