### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by Amanimasila** [foradian/fluxday#51]
--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.1.0/bin/ruby
	--with-mysql-dir
	--without-mysql-dir
	--with-mysql-include
	--without-mysql-include=${mysql-dir}/include
	--with-mysql-lib
	--without-mysql-lib=${mysql-dir}/lib
	--with-mysql-config
	--without-mysql-config
	--with-mysql-dir
	--without-mysql-dir
	--with-mysql-include
	--without-mysql-include=${mysql-dir}/include
	--with-mysql-lib
	--without-mysql-lib=${mysql-dir}/lib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mlib
	--without-mlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-zlib
	--without-zlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-socketlib
	--without-socketlib
	--with-nsllib
	--without-nsllib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mygcclib
	--without-mygcclib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.1.0@fluxday/extensions/x86_64-linux/2.1.0/mysql2-0.3.21/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.1.0@fluxday/gems/mysql2-0.3.21 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.1.0@fluxday/extensions/x86_64-linux/2.1.0/mysql2-0.3.21/gem_make.out
root@ubuntu-s-3vcpu-1gb-blr1-01:~/fluxday/config#

**Comment by Amanimasila** [comment]
any Idea how to solve this

**Comment by Amanimasila** [comment]
To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/usr/local/rvm/gems/ruby-2.1.0@fluxday/extensions/x86_64-linux/2.1.0/mysql2-0.3.21/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/usr/local/rvm/gems/ruby-2.1.0@fluxday/gems/mysql2-0.3.21 for inspection.
Results logged to
/usr/local/rvm/gems/ruby-2.1.0@fluxday/extensions/x86_64-linux/2.1.0/mysql2-0.3.21/gem_make.out

An error occurred while installing mysql2 (0.3.21), and Bundler cannot
continue.
Make sure that `gem install mysql2 -v '0.3.21' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  mysql2
root@ubuntu-s-3vcpu-1gb-blr1-01:~/fluxday# 



the error am getting when trying to build

**Comment by tachyons** [comment]
sudo apt-get install libmysqlclient

**Comment by Amanimasila** [comment]
Thanks it worked
