### ISSUE TITLE
NoMethodError in Projects and Users 

### ISSUE THREAD

**Issue by PlugShubham** [foradian/fluxday#55]
I have followed all the steps for mentioned in documentation. 
I am getting ' undefinef method [] for nil:nilclass wherever project.image.icon or user.image.icon is defined.

**Comment by 1kidvidiot** [comment]
Never able to get it running in any Ubuntu 18.04 or 18.10 server or Debian 9 after trying 5-6x

**Comment by PlugShubham** [comment]
Try with Ruby 2.4 bundler 1.17.3 and carrierwave 1.0.0

**Comment by 1kidvidiot** [comment]
hm how would I execute that in debian 9? Sorry somewhat new, especially ruby on rails - thanks for looking!

**Comment by 1kidvidiot** [comment]
So I have these installed now, and have removed the other versions, and it all installed ok. Should I now run the bundler?

**Comment by PlugShubham** [comment]
Uninstall Ruby and install Ruby 2.3

**Comment by Navinnair** [comment]
user following gem version
**carrierwave (1.0.0)**
**sdoc (0.4.0)**
