### ISSUE TITLE
Use .ruby-version and .ruby-gemset instead of rvmrc

### ISSUE THREAD

**Issue by coderhs** [foradian/fluxday#6]
Presently the project is using `.rvmrc`, but its now depreciated and encouraged to create `.ruby-version` file to specify the ruby version and `.ruby-gemset` file to set the gemset, so that its compatible with other ruby managers as well.

Since we are not using any extra shell scripting in the `.rvmrc` why not change to using `.ruby-version` and `.ruby-gemset` so that it plays nicely with the other version managers.

**Comment by stpnlr** [comment]
fixed in commit https://github.com/foradian/fluxday/commit/492fe147d1cf28eb5cb80cd40d644fb232478a45
