### ISSUE TITLE
Issue starting Server

### ISSUE THREAD

**Issue by jquiyula** [foradian/fluxday#60]
Started GET "/users/sign_in" for 209.118.52.57 at 2019-05-02 18:25:50 +0000
Processing by Devise::SessionsController#new as HTML
Completed 500 Internal Server Error in 38ms

SystemStackError (stack level too deep):
  actionpack (4.0.3) lib/action_dispatch/middleware/reloader.rb:70

**Comment by Navinnair** [comment]
seems like you have missed seeds.

**Comment by Navinnair** [comment]
use **wicked_pdf (0.9.10)**

**Comment by Navinnair** [comment]
@ismudnx this can be closed
