### ISSUE TITLE
undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by Lessad** [foradian/fluxday#69]
Hello folks,

After quite some time figuring out how to install Fluxday properly I can finally get to be connected, I created some users but I cannot assign Managers to teams or anything it would give me this:

undefined method `name' for nil:NilClass

Would someone know a fix for that ? During the installation I tried to use ruby 2.1.0 but it woudnt let me bundle without being at 2.3.0, and I am afraid of the whole thing crumbling down if I dare downgrate it...

Thanks in advance !

**Comment by Lessad** [comment]
You can try it out with this empty fluxday at http://51.38.237.94/

**Comment by Navinnair** [comment]
i have installed the application using ruby 2.1.0 and its working fine for me. Can you please try to install with ruby 2.1.0 and share the error

**Comment by Lessad** [comment]
Retried but it couldn’t work, going to try another tool
