### ISSUE TITLE
DB creation error

### ISSUE THREAD

**Issue by osteth** [foradian/fluxday#8]
I am getting an error building out the DB.  I think it has to do with the version of ruby and mysql.  it looks like this problem has been fixed in the latest version but still persists in 2.1.0  will fluxday work with the current ruby? 

rake db:migrate
(in /root/fluxday)
==  CreateProjects: migrating =================================================
-- create_table(:projects)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead: CREATE TABLE `projects` (`id` int(11) DEFAULT NULL auto_increment PRIMARY KEY, `name` varchar(255), `code` varchar(255), `description` text, `is_deleted` tinyint(1) DEFAULT 0, `created_at` datetime, `updated_at` datetime) ENGINE=InnoDB

**Comment by tachyons** [comment]
Duplicate of #5 ?

**Comment by osteth** [comment]
aah, yeah, that looks to be the same issue.  Closing
